name: windows-latest
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
    secrets:
      TEST_PYPI_API_TOKEN:
        required: true
jobs:
  package:
    uses: ./.github/workflows/test_package_main.yaml
    with:
      os: windows-latest
      python-version: ${{ inputs.python-version }}
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
    permissions:
      id-token: write
