name: macos-13/3.8
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  package:
    uses: ./.github/workflows/test_package_macos-13.yaml
    with:
      python-version: "3.8"
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
    permissions:
      id-token: write
