name: test package
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string
    secrets:
      TEST_PYPI_API_TOKEN:
        required: true
jobs:
  build:
    name: Run tests with pytest
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev,tests]"
      - name: Preparation of pytest
        run: |
          python tests/scripts/download_all.py
      - name: Pytest (run all tests including redundant ones)
        id: run_redundant
        if: startsWith(github.head_ref, 'release/')
        run: |
          pytest --run-redundant -vvv -n 16 --cov=./ssspy --cov-report=xml tests/package/
      - name: Pytest (skip redundant tests)
        if: steps.run_redundant.conclusion == 'skipped'
        run: |
          pytest -vvv -n 16 --cov=./ssspy --cov-report=xml tests/package/
      - name: Pytest (regression tests)
        run: |
          pytest -vvv -n 16 tests/regression/
      - name: Upload coverage to codecov
        if: inputs.python-version == '3.12' && inputs.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
  upload_package:
    needs:
      - build
    permissions:
      id-token: write
    secrets:
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
    if: github.event_name == 'pull_request' && inputs.python-version == '3.12' && inputs.os == 'ubuntu-latest'
    uses: ./.github/workflows/upload_package.yaml
