name: macos-13/3.9
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  package:
    uses: ./.github/workflows/test_package_macos-13.yaml
    with:
      python-version: "3.9"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
    permissions:
      id-token: write
